### ISSUE TITLE
Offline users have a square pfp

### ISSUE THREAD

**Issue by maximeurbn** [kawaiizenbo/Roundrect#2]
As well as many others small issues

**Comment by maximeurbn** [comment]
tagging a channel looks weird

**Comment by maximeurbn** [comment]
![image](https://user-images.githubusercontent.com/22241832/131546112-d0c95623-ee0d-40ef-898f-d358a6d64954.png)

**Comment by kawaiizenbo** [comment]
fixed channel tagging, was an issue with revert rebrand. however i do not know what you are talking about with the square offline user icons. for me they appear as they should

**Comment by maximeurbn** [comment]
I meant that the color was a little off but it might just be an impression

**Comment by maximeurbn** [comment]
the close and minimize buttons are not colored

**Comment by kawaiizenbo** [comment]
yes i removed that as i didnt like it

**Comment by maximeurbn** [comment]
is the color normal?
![2021_09_05_21_44_03_Window](https://user-images.githubusercontent.com/22241832/132139555-df52d427-e8cd-4207-b332-bedaa6289e9b.png)

**Comment by kawaiizenbo** [comment]
probably, i have not 100% tested everything in this theme
