### ISSUE TITLE
Background color in friends tab doesn't match

### ISSUE THREAD

**Issue by HiP3X** [kawaiizenbo/Roundrect#3]
Solution:
Change `.peopleColumn-29fq28` to `.peopleColumn-1wMU14`

**Comment by kawaiizenbo** [comment]
i’m working on it, discord changed a whole bunch of their css class names last night

**Comment by kawaiizenbo** [comment]
currently waiting for a full list of changed classes

**Comment by kawaiizenbo** [comment]
https://github.com/kawaiizenbo/Roundrect/commit/a9197b5712f5f60a49b65a6069e34103af4e5577
